# Use an official Python runtime as a parent image
FROM python:3.12.6-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN git config --global init.defaultBranch main